name: Basic test push

on:
  pull_request:
    types:
      - opened

jobs:
  pr-opened-slack-notifier:
    if: github.event.pull_request.opened == true
    name: Send notification into slack when PR is opened
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Wassup, homey? I miiiissed you"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":mega: *A new pull request is opened, you are rock!*"
                }
              },
              {
                  "type": "section",
                  "fields": [
                      {
                          "type": "mrkdwn",
                          "text": "*Author:*\n${{ github.event.pull_request.user.login }}"
                      },
                      {
                          "type": "mrkdwn",
                          "text": "*Title:*\n${{ github.event.pull_request.title }}"
                      },
                      {
                          "type": "mrkdwn",
                          "text": "*Base branch:*\n${{ github.event.pull_request.base.ref }}"
                      },
                      {
                          "type": "mrkdwn",
                          "text": "*Compare branch:*\n${{ github.event.pull_request.head.ref }}"
                      }
                  ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ secrets.NATERA_DEV_TEAM }}, guys, you know what to do!"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "See Pull Request :point_down::skin-tone-3:",
                    "emoji": true
                  },
                  "url": "${{ github.event.pull_request.html_url }}"
                }
              }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
