name: Basic test push

on:
  pull_request:
    types: [ opened ]

jobs:
  slackNotifier:
    name: Send notification into slack
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "A new Pull Request is coming, you are rock! \n
                       Guys, you know what to do!
                      ",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Here is PR: ${{ job.status }}\n${{ github.event.pull_request.html_url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
