on:
  push:
name: Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Denver
          SLACK_TITLE: A new Pull Request is coming, you are rock!
          SLACK_MESSAGE: 'Guys, you know what to do! @misha.savchuk21 <reviewers>'
          MSG_MINIMAL: true
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: Just a small remider!
