name: Basic test push

on:
  pull_request:
    types: [ opened ]
#                    "text": "Here is PR: ${{ job.status }}\n${{ github.event.pull_request.html_url }}"

jobs:
  slackNotifier:
    name: Send notification into slack
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
          {
            "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": ":mega: *A new Pull Request is coming, you are rock!*"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Guys, you know what to do!"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Click Me :point_down::skin-tone-3:",
                  "emoji": true
                },
                "url": "https://google.com"
              }
            }
            ]
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
