name: Slack PR review notifier!

on:
  pull_request_review:
    types:
      - submitted

jobs:
  notify-dev-team-after-approval:
    if: github.event.review.state == 'approved'
    name: Send notification into slack after PR approval
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":superhero::skin-tone-3: *Improvements are coming!*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "This is looking :sparkles:! ${{ github.event.pull_request.user.login }} left a few comments that should be addresed before this gets merged. :smile_cat:"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Please take a look at comments"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "See Pull Request :point_down::skin-tone-3:",
                    "emoji": true
                  },
                  "url": "${{ github.event.pull_request.html_url }}"
                }
              }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  notify-dev-team-after-comment:
    if: github.event.review.state == 'commented'
    name: Send notification into slack after PR commented
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":building_construction: *Improvements are coming!*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ secrets.NATERA_DEV_TEAM }}, pull request looking :sparkles:!"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.event.review.user.login }}, left a few comments that should be addresed before PR gets merged."
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Please take a look at comments :smile_cat:"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "See Pull Request :point_down::skin-tone-3:",
                    "emoji": true
                  },
                  "url": "${{ github.event.pull_request.html_url }}"
                }
              }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

